### ISSUE TITLE
Crash with Botany Pots 1.19.2

### ISSUE THREAD

**Issue by Gamerbolts** [ianm1647/expandeddelight#40] opened 2023-01-24 22:23 UTC
Hello I am having some issues with the newest version of your mod, it is crashing with Botany Pots. I have the following mods installed:

Bookshelf - 16.2.17
BotanyPots - 9.0.24
Expanded Delight - 0.2.5.1
Fabric API 0.73.0
Farmer's Delight - 1.3.9

The crash happens when having these mods installed and trying to create a new world. Here are the following log and crash log files. Any help is appreciated. Thank you!

[crash-2023-01-24_16.19.03-client.txt](https://github.com/ianm1647/expandeddelight/files/10494510/crash-2023-01-24_16.19.03-client.txt)
[latest.log](https://github.com/ianm1647/expandeddelight/files/10494512/latest.log)

**Comment by VanillaChan6571** [comment] 2023-03-07 03:39
Same issue and confirmed issue, Expanded Delight crashes with BotanyPots on click event crash.

**Comment by ianm1647** [comment] 2023-03-22 04:08
> Hello I am having some issues with the newest version of your mod, it is crashing with Botany Pots. I have the following mods installed:
> 
> Bookshelf - 16.2.17 BotanyPots - 9.0.24 Expanded Delight - 0.2.5.1 Fabric API 0.73.0 Farmer's Delight - 1.3.9
> 
> The crash happens when having these mods installed and trying to create a new world. Here are the following log and crash log files. Any help is appreciated. Thank you!
> 
> [crash-2023-01-24_16.19.03-client.txt](https://github.com/ianm1647/expandeddelight/files/10494510/crash-2023-01-24_16.19.03-client.txt) [latest.log](https://github.com/ianm1647/expandeddelight/files/10494512/latest.log)

i have just tried to recreate the crash and im not experiencing any problems with these two mods, i dont know if its something else, but i created a world just fine. did it happen to you with just these mods loaded or did it happen in a modpack?

**Comment by VanillaChan6571** [comment] 2023-03-23 21:50
BotanyPots must of fixed the issue since this was 2 weeks ago. Also a bunch of mods/apis updated so they could of fixed/bypassed your issue.

**Comment by DJChaos42** [comment] 2023-07-28 17:13
Having an identical issue in 1.20.1. Tested on a brand new Quilt instance with all mods updated to their most recent versions.

[crash-2023-07-28_10.55.49-client.txt](https://github.com/ianm1647/expandeddelight/files/12196699/crash-2023-07-28_10.55.49-client.txt)
[latest.log](https://github.com/ianm1647/expandeddelight/files/12196707/latest.log)

Testing Environment:

Minecraft Version: 1.20.1
Modloader: Quilt 0.20.0-beta4
Launcher: ATLauncher 3.4.30.0

Installed mods:
Bookshelf-Fabric-1.20.1-20.0.2
BotanyPots-Fabric-1.20.1-13.0.2
Expanded Delight 0.3.0.1
Farmer's Delight 1.4.1 - 1.20-1.20.1
QFAPI 7.0.6 and QSL 7.0.6+0.85.0-1.20.1

**Comment by ianm1647** [comment] 2023-07-28 18:27
> 

its a crash with botany pots, at least i think so, does the instance load just fine without expanded delight?

edit: ~~im testing rn~~ its a datapack problem with expanded delight, im looking into it currently

**Comment by ianm1647** [comment] 2023-07-28 19:56
this is now fixed!

**Closed as completed by ianm1647** 2023-07-28 19:56 UTC

**Comment by Darkhax** [comment] 2023-07-28 22:47
@ianm1647 Do you happen to have a stack trace for the actual exception? My deserializer shouldn't be crashing the game so I would like to make make it safe and log a more useful error message.

**Comment by ianm1647** [comment] 2023-07-28 23:22
> @ianm1647 Do you happen to have a stack trace for the actual exception? My deserializer shouldn't be crashing the game so I would like to make make it safe and log a more useful error message.

no i never got around to running a stack trace or anything , i just went in and fixed the data pack error.
